"""Add persona platform models

Revision ID: 1fb4e7ba3426
Revises: 99fef0c70fa3
Create Date: 2025-10-17 23:21:03.216327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb4e7ba3426'
down_revision: Union[str, Sequence[str], None] = '99fef0c70fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create new tables first
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    op.create_table('tools',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('tool_class', sa.String(), nullable=False),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    
    op.create_table('personas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('instructions', sa.Text(), nullable=True),
        sa.Column('agno_team_config', sa.JSON(), nullable=True),
        sa.Column('model_provider', sa.String(), nullable=True),
        sa.Column('model_id', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=False)
    
    op.create_table('user_personas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('persona_id', sa.Integer(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('assigned_by_admin_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_by_admin_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_personas_id'), 'user_personas', ['id'], unique=False)
    
    op.create_table('persona_tools',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('persona_id', sa.Integer(), nullable=False),
        sa.Column('tool_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('added_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
        sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_tools_id'), 'persona_tools', ['id'], unique=False)
    
    op.create_table('tool_usages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('tool_name', sa.String(), nullable=False),
        sa.Column('input_data', sa.JSON(), nullable=True),
        sa.Column('output_data', sa.JSON(), nullable=True),
        sa.Column('execution_time', sa.Float(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_usages_id'), 'tool_usages', ['id'], unique=False)
    
    op.create_table('agent_interactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('agent_name', sa.String(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_interactions_id'), 'agent_interactions', ['id'], unique=False)
    
    op.create_table('conversation_analytics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('total_messages', sa.Integer(), nullable=True),
        sa.Column('total_tool_usages', sa.Integer(), nullable=True),
        sa.Column('total_agent_interactions', sa.Integer(), nullable=True),
        sa.Column('average_response_time', sa.Float(), nullable=True),
        sa.Column('user_satisfaction_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_analytics_id'), 'conversation_analytics', ['id'], unique=False)
    
    # Note: Default admin user and persona should be created using create_admin.py script
    # This ensures proper password hashing and role assignment
    
    # Add nullable columns to existing conversations table first
    op.add_column('conversations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('persona_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('status', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Update existing conversations with default values (only if users and personas exist)
    # If no users/personas exist, these will remain NULL until created
    # Note: user_id and persona_id will be made NOT NULL in a later migration
    # after users and personas are created via the admin script
    op.execute("""
        UPDATE conversations 
        SET user_id = (SELECT id FROM users LIMIT 1),
            persona_id = (SELECT id FROM personas LIMIT 1),
            status = 'active',
            updated_at = NOW()
        WHERE user_id IS NULL 
        AND EXISTS (SELECT 1 FROM users LIMIT 1)
        AND EXISTS (SELECT 1 FROM personas LIMIT 1)
    """)
    
    # Keep columns nullable for now - they will be set to NOT NULL after users/personas are created
    # This allows the migration to succeed even if no users/personas exist yet
    
    # Add foreign key constraints
    op.create_foreign_key('fk_conversations_user_id', 'conversations', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_conversations_persona_id', 'conversations', 'personas', ['persona_id'], ['id'])
    
    # Update messages table
    op.add_column('messages', sa.Column('sender_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('agent_name', sa.String(), nullable=True))
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('messages', 'agent_name')
    op.drop_column('messages', 'sender_type')
    op.drop_constraint('fk_conversations_persona_id', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_conversations_user_id', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'status')
    op.drop_column('conversations', 'persona_id')
    op.drop_column('conversations', 'user_id')
    op.drop_table('conversation_analytics')
    op.drop_table('agent_interactions')
    op.drop_table('tool_usages')
    op.drop_table('persona_tools')
    op.drop_table('user_personas')
    op.drop_table('personas')
    op.drop_table('tools')
    op.drop_table('users')
    # ### end Alembic commands ###
