"""remove_persona_id_add_persona_agent_junction

Revision ID: 6c0e9da29b1e
Revises: a05b5fee1239
Create Date: 2025-10-18 12:53:29.783287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0e9da29b1e'
down_revision: Union[str, Sequence[str], None] = 'a05b5fee1239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_persona_id_fkey'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'persona_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('agents_persona_id_fkey'), 'agents', 'personas', ['persona_id'], ['id'])
    # ### end Alembic commands ###
