"""made multiple db changes

Revision ID: b940a812f440
Revises: 6c0e9da29b1e
Create Date: 2025-10-19 13:25:31.365611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b940a812f440'
down_revision: Union[str, Sequence[str], None] = '6c0e9da29b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables and indexes if they exist (using IF EXISTS for safety)
    # Drop persona_agents table if it exists
    op.execute("""
        DROP TABLE IF EXISTS persona_agents CASCADE;
    """)
    
    # Drop persona_tools table if it exists
    op.execute("""
        DROP TABLE IF EXISTS persona_tools CASCADE;
    """)
    
    # Drop agent_tools table if it exists
    op.execute("""
        DROP TABLE IF EXISTS agent_tools CASCADE;
    """)
    
    # Add new columns to existing tables
    op.add_column('agents', sa.Column('tools', sa.JSON(), nullable=True))
    op.add_column('personas', sa.Column('agents', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'agents')
    op.drop_column('agents', 'tools')
    op.create_table('agent_tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_tools_agent_id_fkey')),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('agent_tools_tool_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_tools_pkey'))
    )
    op.create_index(op.f('ix_agent_tools_id'), 'agent_tools', ['id'], unique=False)
    op.create_table('persona_tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('persona_tools_persona_id_fkey')),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('persona_tools_tool_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('persona_tools_pkey'))
    )
    op.create_index(op.f('ix_persona_tools_id'), 'persona_tools', ['id'], unique=False)
    op.create_table('persona_agents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('attached_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('persona_agents_agent_id_fkey')),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('persona_agents_persona_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('persona_agents_pkey'))
    )
    op.create_index(op.f('ix_persona_agents_id'), 'persona_agents', ['id'], unique=False)
    # ### end Alembic commands ###
