"""added logs tables

Revision ID: c5cf80535b92
Revises: 63908ea7541b
Create Date: 2025-10-20 16:53:01.719689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cf80535b92'
down_revision: Union[str, Sequence[str], None] = '63908ea7541b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists, if not create it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    tables = inspector.get_table_names()
    
    if 'agent_run_logs' not in tables:
        # Create the table with all columns including message_id
        op.create_table('agent_run_logs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('conversation_id', sa.Integer(), nullable=False),
            sa.Column('persona_id', sa.Integer(), nullable=False),
            sa.Column('raw_log', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('message_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
            sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
            sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_agent_run_logs_id'), 'agent_run_logs', ['id'], unique=False)
    else:
        # Table exists, just add the message_id column
        # Check if column already exists
        columns = [col['name'] for col in inspector.get_columns('agent_run_logs')]
        if 'message_id' not in columns:
            op.add_column('agent_run_logs', sa.Column('message_id', sa.Integer(), nullable=True))
            # Update existing rows (if any)
            op.execute("""
                UPDATE agent_run_logs 
                SET message_id = (SELECT id FROM messages LIMIT 1)
                WHERE message_id IS NULL
            """)
            # Make NOT NULL
            op.alter_column('agent_run_logs', 'message_id', nullable=False)
            # Add foreign key
            op.create_foreign_key('agent_run_logs_message_id_fkey', 'agent_run_logs', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agent_run_logs_message_id_fkey', 'agent_run_logs', type_='foreignkey')
    op.drop_column('agent_run_logs', 'message_id')
    # ### end Alembic commands ###
