"""added logs tables

Revision ID: c5cf80535b92
Revises: 63908ea7541b
Create Date: 2025-10-20 16:53:01.719689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cf80535b92'
down_revision: Union[str, Sequence[str], None] = '63908ea7541b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_run_logs', sa.Column('message_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'agent_run_logs', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_run_logs', type_='foreignkey')
    op.drop_column('agent_run_logs', 'message_id')
    # ### end Alembic commands ###
