"""renaming logs table

Revision ID: f29e385c7802
Revises: 638c090131da
Create Date: 2025-10-25 09:44:02.837244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f29e385c7802'
down_revision: Union[str, Sequence[str], None] = '638c090131da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_run_logs_id'), table_name='agent_run_logs')
    op.drop_table('agent_run_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw_log', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('agent_run_logs_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('agent_run_logs_message_id_fkey')),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('agent_run_logs_persona_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_run_logs_pkey'))
    )
    op.create_index(op.f('ix_agent_run_logs_id'), 'agent_run_logs', ['id'], unique=False)
    # ### end Alembic commands ###
